/** @type {import('tailwindcss').Config} */
module.exports = {
  // ...existing code...
  theme: {
    extend: {
      // ...existing code...
      colors: {
        // ...existing colors...
        border: 'hsl(var(--border))',
      },
      // ...existing code...
    },
  },
  // ...existing code...
};
