import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/ui';
import ClientLayout from './ClientLayout';
import { Separator } from '@/components/ui/separator';
import Headers from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Stellar</title>
        <meta name="description" content="" />
      </head>
      <body className="antialiased" suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="Dark"
          enableSystem
          disableTransitionOnChange
        >
          <Headers />
          <Separator />
          <ClientLayout>{children}</ClientLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
